package com.example.bottledwater.entity;

import java.util.Date;

public class DeliveryAssignment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_assignment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_assignment.delivery_person_id
     *
     * @mbggenerated
     */
    private Integer deliveryPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_assignment.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_assignment.assigned_time
     *
     * @mbggenerated
     */
    private Date assignedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_assignment.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_assignment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_assignment.id
     *
     * @return the value of delivery_assignment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_assignment.id
     *
     * @param id the value for delivery_assignment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_assignment.delivery_person_id
     *
     * @return the value of delivery_assignment.delivery_person_id
     *
     * @mbggenerated
     */
    public Integer getDeliveryPersonId() {
        return deliveryPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_assignment.delivery_person_id
     *
     * @param deliveryPersonId the value for delivery_assignment.delivery_person_id
     *
     * @mbggenerated
     */
    public void setDeliveryPersonId(Integer deliveryPersonId) {
        this.deliveryPersonId = deliveryPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_assignment.order_id
     *
     * @return the value of delivery_assignment.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_assignment.order_id
     *
     * @param orderId the value for delivery_assignment.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_assignment.assigned_time
     *
     * @return the value of delivery_assignment.assigned_time
     *
     * @mbggenerated
     */
    public Date getAssignedTime() {
        return assignedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_assignment.assigned_time
     *
     * @param assignedTime the value for delivery_assignment.assigned_time
     *
     * @mbggenerated
     */
    public void setAssignedTime(Date assignedTime) {
        this.assignedTime = assignedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_assignment.status
     *
     * @return the value of delivery_assignment.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_assignment.status
     *
     * @param status the value for delivery_assignment.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_assignment.update_time
     *
     * @return the value of delivery_assignment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_assignment.update_time
     *
     * @param updateTime the value for delivery_assignment.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}