package com.example.bottledwater.entity;

import java.math.BigDecimal;

public class orderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.detail_id
     *
     * @mbggenerated
     */
    private Integer detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.bottled_water_category
     *
     * @mbggenerated
     */
    private String bottledWaterCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.unit_price
     *
     * @mbggenerated
     */
    private BigDecimal unitPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.detail_id
     *
     * @return the value of order_detail.detail_id
     *
     * @mbggenerated
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.detail_id
     *
     * @param detailId the value for order_detail.detail_id
     *
     * @mbggenerated
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_id
     *
     * @return the value of order_detail.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.bottled_water_category
     *
     * @return the value of order_detail.bottled_water_category
     *
     * @mbggenerated
     */
    public String getBottledWaterCategory() {
        return bottledWaterCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.bottled_water_category
     *
     * @param bottledWaterCategory the value for order_detail.bottled_water_category
     *
     * @mbggenerated
     */
    public void setBottledWaterCategory(String bottledWaterCategory) {
        this.bottledWaterCategory = bottledWaterCategory == null ? null : bottledWaterCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.quantity
     *
     * @return the value of order_detail.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.quantity
     *
     * @param quantity the value for order_detail.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.unit_price
     *
     * @return the value of order_detail.unit_price
     *
     * @mbggenerated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.unit_price
     *
     * @param unitPrice the value for order_detail.unit_price
     *
     * @mbggenerated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
}