package com.example.bottledwater.mapper;

import com.example.bottledwater.entity.admin;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface adminMapper {
    admin login(admin rec);
   Integer loginname(admin rec);
    int register(admin rec);
    Integer token(String username);

    int updateAdmin(admin rec,String usernames);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_users
     *
     * @mbggenerated
     */
    int insert(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_users
     *
     * @mbggenerated
     */
    int insertSelective(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_users
     *
     * @mbggenerated
     */
    admin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(admin record);
}