package com.example.bottledwater.mapper;

import com.example.bottledwater.entity.bottledWater;

public interface bottledWaterMapper {
    int insert(bottledWater record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bottled_water
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bottled_water
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bottled_water
     *
     * @mbggenerated
     */
    int insertSelective(bottledWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bottled_water
     *
     * @mbggenerated
     */
    bottledWater selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bottled_water
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(bottledWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bottled_water
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(bottledWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bottled_water
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(bottledWater record);
}