package com.example.bottledwater.mapper;

import com.example.bottledwater.entity.delivery;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface deliveryMapper {
    Integer insert(delivery record);

    Integer deleteByPrimaryKey(Integer id);

    Integer selectIdnumber(delivery delivery);

    Integer selectUsername(delivery delivery);

    Integer selectPhone(delivery delivery);

    List<delivery> selectAll();

    List<delivery> selectLike(String sel);//模糊查询

    Integer updateByPrimaryKey(delivery record);

    delivery selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(delivery record);


    int insertSelective(delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_person
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_person
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_person
     *
     * @mbggenerated
     */

}