package com.example.bottledwater.mapper;

import com.example.bottledwater.entity.deliveryOrder;

public interface deliveryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_assignment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_assignment
     *
     * @mbggenerated
     */
    int insert(deliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_assignment
     *
     * @mbggenerated
     */
    int insertSelective(deliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_assignment
     *
     * @mbggenerated
     */
    deliveryOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_assignment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(deliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_assignment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(deliveryOrder record);
}