package com.example.bottledwater.mapper;

import com.example.bottledwater.entity.Delivery;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DeliveryMapper {
    Integer insert(Delivery record);

    Integer deleteByPrimaryKey(Integer id);

    Integer selectIdnumber(Delivery delivery);

    Integer selectUsername(Delivery delivery);

    Integer selectPhone(Delivery delivery);

    List<Delivery> selectAll();

    List<Delivery> selectLike(String sel); //模糊查询

    Integer updateByPrimaryKey(Delivery record);

    Delivery selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(Delivery record);


    int insertSelective(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_person
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_person
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_person
     *
     * @mbggenerated
     */

}
