package com.example.bottledwater.mapper;

import com.example.bottledwater.entity.userwater;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface userwaterMapper {
    List<userwater> selectAll();
    Integer insert(userwater record);
    Integer selectUsername(userwater userwater);//查询数据库中用户名是否存在
    Integer selectPhone(userwater userwater);//查询数据库中电话是否存在
    Integer selectEmail(userwater userwater);//查询数据库中邮箱是否存在

    userwater selectIdUserwater(int id);

    Integer updateuser(userwater userwater);

    Integer deluser(int id);

    List<userwater> selectUser(String sel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    int insertSelective(userwater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    userwater selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(userwater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(userwater record);
}