package com.example.bottledwater.mapper;

import com.example.bottledwater.entity.UserWater;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserWaterMapper {
    List<UserWater> selectAll();
    Integer insert(UserWater record);
    Integer selectUsername(UserWater userwater); //查询数据库中用户名是否存在
    Integer selectPhone(UserWater userwater); //查询数据库中电话是否存在
    Integer selectEmail(UserWater userwater); //查询数据库中邮箱是否存在

    UserWater selectIdUserwater(int id);

    Integer updateuser(UserWater userwater);

    Integer deluser(int id);

    List<UserWater> selectUser(String sel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    int insertSelective(UserWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    UserWater selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_water
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserWater record);
}
