spring:
  datasource:
    username: root
    password: 13850179569
    url: jdbc:mysql://localhost:3306/bottled_water
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8085
